import HalimeHatunImg from "../../assets/halimeErtugrul.jpg";
import HalimeHatunImg2 from "../../assets/tumbaHalimeErtugrul.jpg";

const HalimeHatunErtugrul = () => {
  return (
    <div className="page-content">
      <h1>Halime Hatun (Esposa de Ertugrul Gazi)</h1>
      <img src={HalimeHatunImg} alt="Halime Hatun" style={{ width: "200px", height: "200px", marginRight: "10px" }} />
      <img src={HalimeHatunImg2} alt="Halime Hatun" style={{ width: "250px", height: "200px"}} />
      <p>Es fundamental empezar con una aclaración importante: al igual que ocurre con Ertuğrul, la figura de Halime Hatun habita en una zona gris entre la realidad histórica documentada y la leyenda. Las fuentes del siglo XIII son muy escasas, por lo que mucho de lo que "sabemos" proviene de tradiciones orales posteriores y del folclore turco.</p>
      <p>Halime Hatun (a veces referida como Halime Sultan o Hafsa Hatun en algunas crónicas) es venerada como la esposa de Ertuğrul Gazi y la madre de Osman I, el fundador del Imperio Otomano. Halime: Es un nombre de origen árabe que significa "Paciente", "Amable" o "Mansa". Un nombre que refleja las virtudes esperadas de una mujer noble de la época. Hatun: No es un apellido, sino un título honorífico utilizado por los pueblos turcos y mongoles equivalente a "Dama", "Señora" o "Reina" (la contraparte femenina de "Khan" o "Bey").</p>
      <p>La narrativa más popular (y la adoptada por la famosa serie Diriliş: Ertuğrul) sostiene que ella era una princesa de sangre real, miembro de la dinastía Selyúcida. Se dice que era hija de Numan, un príncipe selyúcida, y sobrina del sultán Alaaddin Keykubad I. Sin embargo, las evidencias históricas son escasas y la mayoría de esta información proviene de tradiciones posteriores. Muchos historiadores modernos sugieren que esta conexión real podría ser una "fabricación" posterior para legitimar el ascenso de los otomanos, dándoles un linaje que los conectara con la poderosa dinastía anterior (los Selyúcidas). Es posible que simplemente fuera una mujer noble de una tribu turcomana aliada.</p>
      <p>Su unión con Ertuğrul no fue solo un asunto romántico (como se dramatiza en la ficción), sino una alianza estratégica crucial. Si aceptamos la versión de que era princesa selyúcida, su matrimonio simbolizó la transferencia de legitimidad y poder de los Selyúcidas (que estaban en declive) a los Kayı/Otomanos (que estaban en ascenso). Fue una compañera leal que soportó las extremas dificultades de la vida nómada, las guerras fronterizas y las migraciones constantes de la tribu Kayı. Su nombre se ha convertido en un símbolo de la nobleza y la dignidad femenina en la cultura turca.</p>
      <p>Halime Hatun dio a luz a los hijos que asegurarían el futuro de la tribu. Los registros históricos generalmente coinciden en tres hijos principales: Gündüz Alp (o Gündüz Bey): El hijo mayor. Fue un guerrero valiente y figura clave en los primeros años del principado de su hermano menor. Savcı Bey: El hijo mediano. Murió joven en batalla (la Batalla de Domanic) luchando junto a Osman. Osman Gazi (Osman I): El hijo menor y más famoso. Halime es recordada y venerada principalmente por haber dado a luz y criado al hombre que daría nombre al Imperio que duraría 600 años.</p>
      <p>Sobre su muerte xiste una gran confusión debido a la cultura popular moderna. En la Serie de TV: Halime muere joven y trágicamente justo después de dar a luz a Osman. Esto se hizo porque la actriz (Esra Bilgiç) dejó la serie, no por exactitud histórica. En la Historia Real: La mayoría de los historiadores y la tradición coinciden en que Halime Hatun NO murió en el parto. Ella sobrevivió al nacimiento de Osman, crio a sus hijos y se cree que incluso sobrevivió a su esposo Ertuğrul (quien murió anciano). Se estima que falleció alrededor de 1281 o 1282, poco después o antes que su esposo, pero en una edad avanzada para la época. Halime Hatun descansa en Söğüt, la primera capital otomana. Su tumba se encuentra en el jardín del mausoleo de su esposo, Ertuğrul Gazi. La tumba se conoce como "Halime Hatun Kümbeti". Durante siglos, ha sido un lugar de visita para aquellos que desean rendir homenaje a la "madre" del Imperio.</p>
      <p>Halime Hatun representa el arquetipo de la mujer turca fuerte de la estepa: leal, resistente y matriarca. Aunque los detalles de su vida diaria se han perdido en el tiempo, su importancia es indiscutible: sin ella, el linaje de Osman y la historia del Imperio Otomano no habrían existido tal como los conocemos.</p>
    </div>
  )
}

export default HalimeHatunErtugrul